server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loans
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
build:
  version: 10.0.0

loans:
  message: "Welcome to the Loan Management System"
  contactDetails:
    name: "Suraj Kumar"
    email: "Surajkumar@gmail.com"
  onCallSupport: 55555555,66666666666,77777777777