server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/cards
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
