server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cards
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

build:
  version: 2.0.0

cards:
  message: "Welcome to the Card Management System"
  contactDetails:
    name: "John Doe"
    email: "John@gmail.com"
  onCallSupport: 11111111,2222222,33333333
