spring.application.name=accounts


spring.datasource.url=jdbc:postgresql://localhost:5432/easybytes
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG

#first create a table and then initialise a data
spring.jpa.defer-datasource-initialization=true   

build.version=1.0.0

accounts.message=Welcome to the Accounts Application!
accounts.contactDetails.name:Sujay Kumar
accounts.contactDetails.email:sujaykumar94@gmail.com
accounts.onCallSupport:1234567890, 885755466,2225412265
