spring.application.name=accounts


#Below url for connecting to the database in docker container
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/easybytes
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG

#first create a table and then initialise a data
spring.jpa.defer-datasource-initialization=true   
